-- BobloUI 0.11 loader/compiler diagnostic.
local SOURCE = "https://raw.githubusercontent.com/bobloscript/BobloUI/main/dist/BobloUI.lua?cb=" .. tostring(os.time())
print("[BobloUI 0.11 diagnostic] URL:", SOURCE)
assert(typeof(loadstring) == "function", "loadstring unavailable")
local ok, source = pcall(function()
	return game:HttpGet(SOURCE)
end)
assert(ok, "HttpGet failed: " .. tostring(source))
print("[BobloUI 0.11 diagnostic] bytes:", #source)
local chunk, compileError = loadstring(source)
assert(chunk, "[BobloUI 0.11 diagnostic] COMPILE FAILED:\n" .. tostring(compileError))
local runOk, result = pcall(chunk)
assert(runOk, "[BobloUI 0.11 diagnostic] RUNTIME FAILED:\n" .. tostring(result))
assert(type(result) == "table", "bundle did not return a table")
assert(result.Version == "0.11.5-beta.1", "wrong published version: " .. tostring(result.Version))
assert(result.ApiLevel >= 11, "ApiLevel < 11")
print("[BobloUI 0.11 diagnostic] PASS", result.Version, result.ApiLevel)
