--!nonstrict
local hex = Color3.fromHex
return {
	Canvas = hex("#F5F6F8"),
	Background = hex("#F5F6F8"),
	Sidebar = hex("#F8F9FB"),
	Surface = hex("#FFFFFF"),
	SurfaceRaised = hex("#FFFFFF"),
	SurfaceInset = hex("#F1F3F6"),
	SurfaceSecondary = hex("#F0F2F5"),
	SurfaceHover = hex("#E9ECF1"),
	SurfaceActive = hex("#E1E5EB"),
	Control = hex("#F8F9FB"),
	ControlHover = hex("#F2F4F7"),
	ControlPressed = hex("#EAEDF2"),
	ControlInset = hex("#FFFFFF"),
	BorderSubtle = hex("#E7EAF0"),
	Border = hex("#DDE2E9"),
	BorderStrong = hex("#C8D0DB"),
	Text = hex("#15181D"),
	TextSecondary = hex("#586372"),
	TextTertiary = hex("#7F8998"),
	TextDisabled = hex("#AAB2BE"),
	Accent = hex("#6E5DE7"),
	Success = hex("#169D63"),
	Warning = hex("#B77A09"),
	Error = hex("#D84A50"),
	Info = hex("#147FBE"),
	Scrim = hex("#15181D"),
	ScrimTransparency = 0.58,
}
