--!nonstrict
local hex = Color3.fromHex
return {
	Canvas = hex("#F7F7F9"),
	Background = hex("#F7F7F9"),
	Sidebar = hex("#F3F3F5"),
	Surface = hex("#FFFFFF"),
	SurfaceRaised = hex("#FFFFFF"),
	SurfaceInset = hex("#EFEEEE"),
	SurfaceSecondary = hex("#EEEDEF"),
	SurfaceHover = hex("#E8E8EB"),
	SurfaceActive = hex("#E0E0E3"),
	Control = hex("#F5F5F7"),
	ControlHover = hex("#F0F0F2"),
	ControlPressed = hex("#E8E8EB"),
	ControlInset = hex("#FFFFFF"),
	BorderSubtle = hex("#E4E4E8"),
	Border = hex("#DCDCE0"),
	BorderStrong = hex("#C8C8CC"),
	Text = hex("#18181B"),
	TextSecondary = hex("#606068"),
	TextTertiary = hex("#8A8A90"),
	TextDisabled = hex("#ACACB0"),
	Accent = hex("#6B5BE0"),
	Success = hex("#168F5C"),
	Warning = hex("#9A6808"),
	Error = hex("#C83838"),
	Info = hex("#1478B0"),
	Scrim = hex("#18181B"),
	ScrimTransparency = 0.58,
}
